# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

longest_common_subseq <- function(x, y) {
    .Call('_stringproc_longest_common_subseq', PACKAGE = 'stringproc', x, y)
}

